# Generated by Django 4.2.3 on 2023-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
